### ISSUE TITLE
zIndex prop is not bind correctly

### ISSUE THREAD

**Issue by theotimepoisseau-bib** [peterpalau/react-bnb-gallery#24]
Hello,

I didn't understand why the zIndex I passed in `ReactBnbGallery` was not working.
So I looked into the code :
https://github.com/peterpalau/react-bnb-gallery/blob/3cc13731afa21c968336a310099ac12cc4c974a4/src/ReactBnbGallery.js#L170

zIndex is not an HTML attribute but a CSS Property:
So it should be bind pretty much like that :
```js
<div
  style={{zIndex: zindex}}
  // ...
/>
```

**Comment by peterpalau** [comment]
Hello @theotimepoisseau-bib, 

Yes, you are right.

I will fix it right now.

**Comment by peterpalau** [comment]
Hi @theotimepoisseau-bib,

You are right sir. 

Let met fix it right now.

**Comment by theotimepoisseau-bib** [comment]
Hi,

When it'll be released ?

Best regards
