### ISSUE TITLE
The styles are not loaded after buld the entire project

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [peterpalau/react-bnb-gallery#26]
Hello,

After build the my project where I am using the React-bnb-Gallery, the component lose its styles. 
![image](https://user-images.githubusercontent.com/1837416/70820667-8550df80-1dd9-11ea-9b7e-a6fc2db183ce.png)

But in development mode it works fine.
![image](https://user-images.githubusercontent.com/1837416/70820732-a9142580-1dd9-11ea-8eae-32485b4d7a2a.png)

**Comment by programmerrrr** [comment]
+1
Same problem here

**Comment by danhollick** [comment]
Same here, except I am having this issue on my dev server too. 
Using next.js.

**Comment by peterpalau** [comment]
Hi all,

Have you tried the following in your projects?

```
import 'react-bnb-gallery/dist/style.css';
```

**Comment by danhollick** [comment]
@peterpalau that seems to work. But the styling seems to be a bit broken. There is no padding on top of the main image preview.
<img width="719" alt="Screenshot 2019-12-20 at 16 43 54" src="https://user-images.githubusercontent.com/13898607/71266076-f0556580-2347-11ea-8cad-0f0f04121f75.png">

**Comment by JClackett** [comment]
I also have the same as @danhollick, using next.js

**Comment by panczarny** [comment]
+1 broken styles in my code 😿

**Comment by filippofortino** [comment]
Yup, i'm also using next.js and have the same issue as @danhollick

**Comment by peterpalau** [comment]
Hey guys I'm going to test this using the mentioned environment with `Next.js`. 

Thanks to all for your interest in this project.

**Comment by peterpalau** [comment]
I tested this and it's working good.
