### ISSUE TITLE
Causes errors in browser Electron v59

### ISSUE THREAD

**Issue by Neilpoulin** [peterpalau/react-bnb-gallery#3]
This library is great! I'm excited to use it in my app, but I ran into a problem while running my end-to-end tests (via Cypress). These tests run my app in a headless browser, in this case, Electron (version 59). When I include this library, it crashes the app. 

Any idea what might be going on?

Maybe random and unhelpful tidbits:

Here's the only error I get in my console logs when I have react-bnb-gallery on the page (the error goes away when I remove the component)
![image](https://user-images.githubusercontent.com/802410/53131039-ffe9ff00-3528-11e9-9177-74a9ac2fff84.png)

When clicking into the error link (VM296 main.js:40709) I get this: 
![image](https://user-images.githubusercontent.com/802410/53131125-2c058000-3529-11e9-8711-b1f42f3fdbfa.png)

I suspect it's actually from Sentry, but can't be sure right now. It's worth calling out that i'm using react-hot-loader

**Comment by peterpalau** [comment]
@Neilpoulin Thank you. I will try to reproduce the bug but I also think it can be a problem with Sentry.
