### ISSUE TITLE
Error in the 'Getting Started' Example (missing wrapping element)

### ISSUE THREAD

**Issue by Avivhdr** [peterpalau/react-bnb-gallery#34]
This code is copied from [getting started](https://peterpalau.github.io/react-bnb-gallery/#/getting-started) page in your documentation site.

![image](https://user-images.githubusercontent.com/23265867/83963042-227d6400-a8a3-11ea-958e-ac821b12a506.png)

**Comment by Avivhdr** [comment]
The style imports are also missing in the example page:

`  import 'react-bnb-gallery/dist/style.css';`

**Comment by peterpalau** [comment]
Hi @Avivhdr, I'm sorry you are having this issue.

I updated the **Getting started** example because it was wrong.

Now should be working.

Thanks.

**Comment by peterpalau** [comment]
Please feel free to reopen this issue if you find any other error on the example.
