### ISSUE TITLE
Missing react-bnb-gallery/dist/style.css

### ISSUE THREAD

**Issue by petrpisek** [peterpalau/react-bnb-gallery#36]
Hi,

Thank you for the gallery, it's a great component, we are using it on [https://ascendero.com](https://ascendero.com).

It seems react-bnb-gallery/dist/style.css is not present in the package anymore, can you please check?

Thanks
Petr

**Comment by peterpalau** [comment]
Hi @petrpisek, thank you ver much for your interest in this component.

I will check this issue.

**Comment by peterpalau** [comment]
Hi again @petrpisek, you were right and I fixed the issue and it has been published to [npm](https://www.npmjs.com/package/react-bnb-gallery).
