### ISSUE TITLE
unable to open Clicked image.

### ISSUE THREAD

**Issue by MaheshK02** [peterpalau/react-bnb-gallery#5]
when I clicked on any image of the slider, every time 1st image of the array is opened. 
how to pass the current image or clicked image id to open that specific image.

**Comment by peterpalau** [comment]
Hi @MaheshK02, you can use the `activePhotoIndex` (zero-based) prop to show the current image.

**Comment by MaheshK02** [comment]
activePhotoIndex its not working for me.
example code:-
`
                                    this.state.photos.length > 0 && 
                                        this.state.photos.map((item, index) => (   
                                            <div>
                                                <ReactBnbGallery
                                                        show={this.state.galleryOpened}
                                                        photos={this.state.photos}
                                                        onClose={this.toggleGallery}
                                                        activePhotoIndex={index} />
                                                        
                                                <Image src={item.photo} onClick={this.toggleGallery} className="p-s-img" />
                                            </div>
                                        ))   
                                }`

**Comment by peterpalau** [comment]
Hi @MaheshK02, I have tried this but it works as is expected. 

Could you tell me if it works for you and if is true, kindly close this issue?

**Comment by MaheshK02** [comment]
its works for me. thanx @peterpalau
