### ISSUE TITLE
Unable to remove button outline

### ISSUE THREAD

**Issue by iozeen** [peterpalau/react-bnb-gallery#6]
Hi. Great library thanks for sharing. I wonder how can I style buttons, I need to remove blue outline.

**Comment by peterpalau** [comment]
Hi @iozeen, each button has a class name, please refer to `.gallery-control` css style selector to remove the `outline`.

Code:
```
.gallery-control:focus {
   outline: none;
}
```
The same for `.gallery-close` button.

**Comment by peterpalau** [comment]
Hi @iozeen 

Did the suggestion that I recommended works?
